### ISSUE TITLE
New section about increasing intelligence misrepresents PauseAI

### ISSUE THREAD

**Issue by Wituareard** [PauseAI/pauseai-website#249]
In my opinion, the section added in cc918d8 reads a bit as if transhumanism and eugenics were consensus within PauseAI, especially "A lot of people are sympathetic to this strategy", which has a huge potential to alienate people. Maybe we should aim for something more like "of course, each of these strategies comes with their own strength and weaknesses which can be discussed during a pause".

**Comment by anthonybailey** [comment]
Not sure "eugenics" was merited there, but I grant any germ-line editing
talk wanders towards those danger zones and TESCREAL triggers.

Overall I agree: directly linking semi-baked LessWrong lists and tweets is
not a good look, nor representative of any movement consensus. I venture
the thing we agree on is that there a variety of controversial ideas that
need time and space for discussion.

**Comment by Will9371** [comment]
One angle we could use here: 

Increasing our intelligence to keep up with AI is one approach that some people have suggested for navigating the dangerous period ahead.  This approach, however, is very controversial because it moves distressingly close to eugenics.  Right now, discussions on this topic are mostly theoretical.  But as dangers from AI loom increasingly close, society may be forced to confront these kind of terrible decisions.  At PauseAI, our hope is to make easy choices today--like stopping the frontier training runs that bring us closer to AGI--so we don't have to make hard choices tomorrow.

**Comment by Pato-desu** [comment]
Point taken. I've deleted it given I was the one who added it.
