### ISSUE TITLE
Add to SOTA: worse than humans at agency

### ISSUE THREAD

**Issue by Pato-desu** [PauseAI/pauseai-website#57]
To be a little more honest, and sympathize with skeptics. We can add there that even if LLMs right now aren't agentic the big labs are trying to change that.

**Comment by joepio** [comment]
Yeah the SOTA needs some more things AIs aren't good at. However, I don't think agency is that clear to me. The reason that AutoGPT doesn't really lead to useful behaviour has to do with a bunch of underlying shortcomings:

- Short context window (little short-term memory)
- Hallucinations
- Can't update own weights (learn as you go).

**Comment by Pato-desu** [comment]
I don't know if I agree with you, but I guess agency can mean two different things. One is acting like an agent and the other deciding stuff somewhat independently. Right now they are "bad" for both.

**Comment by joepio** [comment]
What does it mean to "act like an agent", though? I just don't have a clear understanding of this concept I suppose.

We have NN's playing all sorts of video games. I'd consider these agents. They perform actions in a system to achieve some objective. 

I agree that if you give AutoGPT a goal, it performs sub-human in pretty much any task. But I think the reason it's bad can be explained mostly by other shortcomings: it can't make a cup of coffee because it can't control a body. It can't reliably perform tasks as it hallucinates things. 

But maybe I'm missing some important other dimension here?

**Comment by Pato-desu** [comment]
Yeah, you're right. I'm not sure what I wanted to refer to. I'm confused now.

**Comment by Pato-desu** [comment]
Being general purpose?

**Comment by joepio** [comment]
Still not clearly defined to me.

**Comment by Pato-desu** [comment]
> I agree that if you give AutoGPT a goal, it performs sub-human in pretty much any task. But I think the reason it's bad can be explained mostly by other shortcomings: it can't make a cup of coffee because it can't control a body. It can't reliably perform tasks as it hallucinates things.
> 
> But maybe I'm missing some important other dimension here?

Why is the reason why is bad relevant? 
Do you think "Accomplishing instructed goals" is a good term for the thing we are referring to?
Also, they are bad at "Coming up with goals" IMO. So I would prefer if we had something like "Accomplishing goals for which they were not trained"
